version: "3"

services:
  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"
    networks:
      - kafka_test
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka_test
    container_name: kafka
  kafka-manager:
    image: kafkamanager/kafka-manager:3.0.0.4
    ports:
      - "9000:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka_test
    container_name: kafka-manager
networks:
  kafka_test:
