version: "3"

services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    network_mode: host
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    environment:
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
    depends_on:
      - zookeeper
    container_name: kafka
    network_mode: host
